### ISSUE TITLE
Implement Geolexica site for ISO 14812

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/isotc204.geolexica.org#1]
The terminology is available at:
* https://github.com/ISO-TC204/iso14812
* https://github.com/metanorma/iso-14812/

**Comment by ronaldtse** [comment]
This task is dependent on: https://github.com/metanorma/iso-14812/issues/3

**Comment by ronaldtse** [comment]
The terms are imported in #2 .

@HassanAkbar can you duplicate the setup at https://github.com/geolexica/isotc211.geolexica.org and apply it to this current repo, so that the site can be built (and served)? Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse Currently [jekyll-geolexica](https://github.com/geolexica/geolexica-server) gem is used to render concepts on the site according the `old glossarist` model and the concepts that I extracted at https://github.com/geolexica/isotc204.geolexica.org/pull/2 are in `new glossarist` model format.

Should I update the extracted concepts to use the old glossarist format or update the [jekyll-geolexica](https://github.com/geolexica/geolexica-server) gem (this will affect the publishing of new https://github.com/geolexica/isotc211.geolexica.org site)?

**Comment by ronaldtse** [comment]
@HassanAkbar please help update the jekyll-geolexica gem to use the new glossarist model format.

Once we have the isotc204.geolexica.org site working, please help migrate the isotc211.geolexica.org site to the new glossarist format. Thanks.

**Comment by HassanAkbar** [comment]
These are in about and feedback page of TC 211 site
1.
```
Identified issues that are publicly visible are maintained at the
https://github.com/ISO-TC211/TMG/issues[TMG GitHub Issues] page.
```

2.
```
The MLGT spreadsheet and corresponding documentation can be downloaded
from the
https://committee.iso.org/sites/tc211/home/re.html[ISO/TC 211 Resources page].
```

3.
```
The online version of ISO/TC 211 MLGT is jointly managed by the TMG and
https://www.ribose.com/[Ribose],
the official ISO/TC 211 web service provider and
Registration Authority of the
https://geodetic.isotc211.org/[ISO Geodetic Register].
```

4.
```
This is the feedback form link for 211

++++
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScdRwjGvHl1r4DamABqb1uQp7MQdsB-1s3vZHPBiKIKVNFMlQ/viewform?embedded=true" width="640" height="871" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
++++
```

@ronaldtse Where can I find the corresponding links for TC 204 site?

**Update**

```
google_analytics:
  id: UA-168998071-2
```
This is the google analytics tag for `geolexica 211` site, should I use the same or different tag for `geolexica 204` site?

```
social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374
```
And what are the social links for `geolexica 204` site?

**Comment by ronaldtse** [comment]
We have to remove those links in the TC 204 version. Instead, please copy/paste the above text into a new ticket so we can discuss and revamp the page. Thanks!

**Comment by ronaldtse** [comment]
We can add a link to the https://github.com/ISO-TC204/iso14812 repository, which is where the terms originate from.
