### ISSUE TITLE
AWS deployment key not working

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/isotc204.geolexica.org#5]
```sh
$ aws s3 ls isotc204-geolexica-org

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

The deploy key pair does not seem to have proper permissions.

@kwkwan can you please help check the keys/secrets? Thanks!

**Comment by kwkwan** [comment]
The name of the s3 bucket described in s3 policy has been changed from isotc204geolexica.org to isotc204-geolexica-org.

**Comment by ronaldtse** [comment]
Thank you @kwkwan ! Deploy worked at https://github.com/geolexica/isotc204.geolexica.org/actions/runs/2712419316
