### ISSUE TITLE
Concept relations should be resolved to links

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/isotc204.geolexica.org#8]
https://isotc204.geolexica.org/concepts/3.7.1.5/
<img width="1036" alt="Screenshot 2022-07-22 at 3 54 26 PM" src="https://user-images.githubusercontent.com/11865/180381365-425baaf8-621a-4a18-8d9a-6a92a4939928.png">

See the terms:
```
{{vehicle input device,input device}} designed to be physically {{connected}} to a {{vehicle}}
```

These are links to the other concepts defined in the concept collection. We have to make them into links.

Ideally, we should assign URNs to those concepts, e.g. for "input device" `urn:relaton:concept:14812:3.x.x`, and have a resolver for these global IDs.

**Comment by ronaldtse** [comment]
The coding should be done in the isotc211-glossary repo.

**Comment by HassanAkbar** [comment]
Just wanted to make sure that I am going in the right direction. This is what I understand

- Create a processor for `urn:iso-tc:14812:3.x.x` in `relaton-iso`
- Convert text inside `{{}}` into `urn` format inside `yaml` files
- Resolve the references when generating the site.

 @ronaldtse Is this the correct approach?

**Comment by ronaldtse** [comment]
@HassanAkbar yes, I believe that is the correct approach. In the content, we should also embed the text actually rendered (e.g. `{{urn:iso:std:iso:14812:clause:3.1.4.2,vehicle input device,input device}}`)

What we need to specifically do is about defining the URN to be used;
* ISO does have [RFC 5141](https://datatracker.ietf.org/doc/html/rfc5141) that does describe how to identify clause numbers.
* We have the `pubid-iso` gem that builds RFC 5141 URNs using the document identifier
* `pubid-iso` does not support functionality to incorporate clause number (e.g. it produces `urn:iso:std:iso:10993:-4:amd:2006:v1:en` but not  `urn:iso:std:iso:10993:-4:amd:2006:v1:en:3.x.x` (not the exact syntax).

When we build the site, we need to resolve the URNs so in the presentation, we need to:
- link to the concept in HTML
- show the "concept that is being linked", e.g. for the example of "vehicle input device", show "input device"

The syntax is:
```
{{URN,term referenced,term to show}}
```

where
* `URN` is the URN assigned
* `term referenced` is the original term identified by the URN
* `term to show` is the term to be displayed in text

Please let me know if there is anything unclear.

**Comment by HassanAkbar** [comment]
@ronaldtse I was looking into this and tried using `pubid-iso` gem. According to what I found `pubid-iso` does not parse the reference if I pass it like `ISO/TC 204` unless I append a ` N<digit>` at the end like `ISO/TC 204 N3`. But If I use Relaton to search the code like this it gives error stating `no match found online`

```bash
:153 > db.fetch("ISO/TC 204 N3")
[relaton-iso] ("ISO TC 204 N3") fetching...
[relaton-iso] Attempting ISO/IEC retrieval
[relaton-iso] WARNING: no match found online for ISO/IEC TC 204 N3. The code must be exactly like it is on the standards website.
[relaton-iso] If you wanted to cite all document parts for the reference, use "ISO/IEC TC 204 N3 (all parts)".
If the document is not a standard, use its document type abbreviation (TS, TR, PAS, Guide).
```

Am I missing something here?

**Comment by ronaldtse** [comment]
Yes, this is unexpected because pubid-iso only accepts "ISO PubIDs" in the pattern like "ISO 8601-1:2019". These are ISO standards.

The pattern "ISO/TC 204" is not for a source -- it is an identifier for the Technical Committee group within ISO.

Where are you getting this?

For all concepts in this dataset right now, the only source is the document "ISO 14812:2022".

**Comment by HassanAkbar** [comment]
I have update the glossary to include `urn` in this [PR](https://github.com/geolexica/isotc204-glossary/pull/6), and locally it is now linking correctly for html. 
@ronaldtse My question is what should I do in case of other format i.e `json`, `jsonld`, `rdf` etc?

**Comment by ronaldtse** [comment]
> what should I do in case of other format i.e json, jsonld, rdf etc

Use the URNs in those places as well. It is up to the API consumer to understand them.
